# Name of your workflow
name: Test Workflow

# Define the trigger event(s)
on: [push, pull_request]

# Jobs run in parallel by default, each runs steps in sequence
jobs:
    
    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, GitHub Actions!"
        